
  var body = '';

  body += '<div class="breadcrumb">';
  body += '  <a href="/">首页</a> <span class="sep">/</span>';
  body += '  <a href="/forum" id="breadcrumbForum">论坛</a> <span class="sep" id="breadcrumbSep2">/</span>';
  body += '  <a href="/forum" id="breadcrumbCategory" style="display:none;"></a> <span class="sep" id="breadcrumbSep3" style="display:none;">/</span>';
  body += '  <span class="current" id="breadcrumbTitle">帖子详情</span>';
  body += '</div>';

  body += '<div class="page-layout">';
  body += '  <div class="content-area">';
  body += '    <div class="post-detail" id="postDetail">';
  body += '      <div class="loading"><div class="spinner"></div>加载中...</div>';
  body += '    </div>';
  body += '    <div style="margin-bottom:30px;" id="likeArea"></div>';

  body += '    <div class="comment-section">';
  body += '      <h2 class="section-title"><span class="icon">💬</span> 评论区 <span id="commentCount" style="font-size:0.85rem;color:var(--muted);font-weight:400;"></span></h2>';
  body += '      <div class="comment-form" id="commentForm">';
  body += '        <div class="form-group">';
  body += '          <textarea class="form-input" id="commentContent" placeholder="写下你的评论..." rows="3"></textarea>';
  body += '        </div>';
  body += '        <div style="display:flex;justify-content:flex-end;">';
  body += '          <button class="btn btn-primary btn-sm" onclick="submitComment()">发表评论</button>';
  body += '        </div>';
  body += '      </div>';
  body += '      <div class="comment-list" id="commentList">';
  body += '        <div class="loading"><div class="spinner"></div>加载中...</div>';
  body += '      </div>';
  body += '    </div>';
  body += '  </div>';

  body += '  <aside class="sidebar">';
  body += '    <div class="widget">';
  body += '      <h3 class="widget-title">📖 相关文章</h3>';
  body += '      <div class="hot-list" id="relatedPosts">';
  body += '        <div class="loading"><div class="spinner"></div>加载中...</div>';
  body += '      </div>';
  body += '    </div>';
  body += '    <div class="ad-banner">广告位</div>';
  body += '    <div class="widget">';
  body += '      <h3 class="widget-title">🏷️ 热门标签</h3>';
  body += '      <div class="tag-cloud" id="postTags"></div>';
  body += '    </div>';
  body += '  </aside>';
  body += '</div>';

  var pageScript = '';
  pageScript += '<script>';
  pageScript += '(function() {';
  pageScript += '  const postId = window.location.pathname.split("/post/")[1];';
  pageScript += '  let postData = null;';
  pageScript += '  async function loadPost() {';
  pageScript += '    try {';
  pageScript += '      const res = await fetch("/api/posts/" + postId);';
  pageScript += '      const data = await res.json();';
  pageScript += '      if (data.code === 200) { postData = data.data.post; renderPost(data.data); }';
      let reviewHtml = "";
      if (post.review_status === "pending") {
        reviewHtml = '<div style="background:rgba(255,193,7,0.1);border:1px solid rgba(255,193,7,0.3);border-radius:8px;padding:12px 16px;margin-bottom:16px;font-size:0.9rem;color:#856404;">⏳ 该帖子正在审核中，审核通过后将对外展示。</div>';
      } else if (post.review_status === "rejected") {
        reviewHtml = '<div style="background:rgba(231,76,60,0.08);border:1px solid rgba(231,76,60,0.2);border-radius:8px;padding:12px 16px;margin-bottom:16px;font-size:0.9rem;color:#c0392b;">❌ 该帖子未通过审核，请修改后重新提交。</div>';
      }
  pageScript += '      else { document.getElementById("postDetail").innerHTML = \'<div class="empty-state"><div class="empty-icon">😕</div><p>帖子不存在或已被删除</p></div>\'; }';
  pageScript += '    } catch(e) { console.error(e); }';
  pageScript += '  }';
  pageScript += '  function renderPost(data) {';
  pageScript += '    const post = data.post;';
  pageScript += '    const media = data.media || [];';
  pageScript += '    document.getElementById("breadcrumbTitle").textContent = post.title;
    if (post.category) {
      const catMap = {
        'cat-feed':'猫咪饲养','dog-feed':'狗狗饲养','exotic-pet':'小众宠物','food-review':'粮食测评','product-review':'用品测评',
        'cat-disease':'猫咪疾病','dog-disease':'狗狗疾病','daily-care':'日常护理','medical-help':'就医求助',
        'city-adoption':'同城无偿领养','city-breed':'同城配种','lost-found':'寻宠启事','city-walk':'同城遛宠聚会',
        'daily-show':'萌宠日常','pet-contest':'萌宠评选大赛','fun-topic':'趣味养宠话题',
        'secondhand':'宠物用品闲置','pet-transfer':'家养宠物转让','service':'上门寄养/洗护预约',
        'behavior-help':'养宠行为求助','blacklist':'宠物店/粮品避雷','rescue':'流浪宠物救助'
      };
      const catName = catMap[post.category] || post.category;
      const catEl = document.getElementById("breadcrumbCategory");
      catEl.textContent = catName;
      catEl.href = '/forum?category=' + encodeURIComponent(post.category);
      catEl.style.display = '';
      document.getElementById("breadcrumbSep3").style.display = '';
    }';
  pageScript += '    document.title = post.title + " - 毛茸茸星球";';
  pageScript += '    const avatarHtml = (post.user_avatar_url || post.avatar)';
  pageScript += '      ? \'<div class="author-avatar">\' + (post.user_avatar_url ? \'<img src="\' + post.user_avatar_url + \'">\' : post.avatar) + \'</div>\'';
  pageScript += '      : \'<div class="author-avatar">🐱</div>\';';
  pageScript += '    let mediaHtml = "";';
  pageScript += '    if (media.length > 0) {';
  pageScript += '      mediaHtml = \'<div class="post-media">\';';
  pageScript += '      media.forEach(m => {';
  pageScript += '        if (m.media_type === "image") mediaHtml += \'<img src="\' + m.media_url + \'" alt="' + escapeHtml(post.title).substring(0,30) + ' 实拍" loading="lazy" onload="this.classList.add('loaded')">\';';
  pageScript += '        else if (m.media_type === "video") mediaHtml += \'<video src="\' + m.media_url + \'" controls preload="metadata"></video>\';';
  pageScript += '      });';
  pageScript += '      mediaHtml += "</div>";';
  pageScript += '    }';
  pageScript += '    let tagsHtml = "";';
  pageScript += '    if (post.tags) {';
  pageScript += '      const tags = post.tags.split(",");';
  pageScript += '      tagsHtml = tags.map(t => \'<a href="/search?keyword=\' + encodeURIComponent(t.trim()) + \'" class="tag">\' + t.trim() + \'</a>\').join(" ");';
  pageScript += '      document.getElementById("postTags").innerHTML = tagsHtml;';
  pageScript += '    }';
  pageScript += '    document.getElementById("likeArea").innerHTML = \'<button class="like-btn" id="likeBtn" onclick="toggleLike()">❤️ <span>\' + (post.like_count || 0) + \'</span></button>\';';
  pageScript += '    document.getElementById("postDetail").innerHTML =';
  pageScript += '      \'<h1 class="post-title">\' + escapeHtml(post.title) + \'</h1>\' +';
  pageScript += '      \'<div class="post-meta">\' +';
  pageScript += '        \'<div class="author-info">\' + avatarHtml + \'<span class="post-author">\' + (post.username || "匿名") + \'</span></div>\' +';
  pageScript += '        \'<span>\' + formatDate(post.created_at) + \'</span>\' +';
  pageScript += '        \'<span>👁 \' + (post.view_count || 0) + \' 浏览</span>\' +';
  pageScript += '        \'<span>💬 \' + (post.comment_count || 0) + \' 评论</span>\' +';
  pageScript += '      \'</div>\' + mediaHtml +';
  pageScript += '      \'<div class="post-body">\' + (post.content || "") + \'</div>\' +';
  pageScript += '      (tagsHtml ? \'<div style="margin-top:16px;">\' + tagsHtml + \'</div>\' : "");';
  pageScript += '    renderComments(data.comments);';
  pageScript += '    loadRelatedPosts(post.post_type);';
  pageScript += '  }';
  pageScript += '  function renderComments(comments) {';
  pageScript += '    const list = document.getElementById("commentList");';
  pageScript += '    document.getElementById("commentCount").textContent = "(" + (comments ? comments.length : 0) + ")";';
  pageScript += '    if (!comments || comments.length === 0) { list.innerHTML = \'<div class="empty-state"><div class="empty-icon">💭</div><p>暂无评论，来说两句吧~</p></div>\'; return; }';
  pageScript += '    list.innerHTML = comments.map(c => renderCommentItem(c)).join("");';
  pageScript += '  }';
  pageScript += '  function renderCommentItem(c) {';
  pageScript += '    const avatarHtml = c.avatar ? (c.avatar.startsWith("http") ? \'<img src="\' + c.avatar + \'">\' : c.avatar) : "🐱";';
  pageScript += '    let repliesHtml = "";';
  pageScript += '    if (c.replies && c.replies.length > 0) {';
  pageScript += '      repliesHtml = \'<div class="comment-replies">\' + c.replies.map(r => renderCommentItem(r)).join("") + \'</div>\';';
  pageScript += '    }';
  pageScript += '    return \'<div class="comment-item">\' +';
  pageScript += '      \'<div class="comment-avatar">\' + avatarHtml + \'</div>\' +';
  pageScript += '      \'<div class="comment-body">\' +';
  pageScript += '        \'<div class="comment-header"><span class="comment-author">\' + (c.username || "匿名") + \'</span><span class="comment-time">\' + formatDate(c.created_at) + \'</span></div>\' +';
  pageScript += '        \'<div class="comment-text">\' + escapeHtml(c.content) + \'</div>\' +';
  pageScript += '        \'<div class="comment-actions"><button onclick="replyTo(\\\'\' + (c.username || "") + \'\\\')">↩️ 回复</button></div>\' +';
  pageScript += '        repliesHtml + \'</div></div>\';';
  pageScript += '  }';
  pageScript += '  window.submitComment = async function() {';
  pageScript += '    const token = localStorage.getItem("token");';
  pageScript += '    if (!token) { openModal("loginModal"); return; }';
  pageScript += '    const content = document.getElementById("commentContent").value.trim();';
  pageScript += '    if (!content) { showToast("请输入评论内容", "error"); return; }';
  pageScript += '    try {';
  pageScript += '      const res = await authFetch("/api/comments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ post_id: postId, content }) });';
  pageScript += '      const data = await res.json();';
  pageScript += '      if (data.code === 201 || data.code === 200) { showToast("评论成功", "success"); document.getElementById("commentContent").value = ""; loadComments(); }';
  pageScript += '      else { showToast(data.message || "评论失败", "error"); }';
  pageScript += '    } catch(e) { showToast("网络错误", "error"); }';
  pageScript += '  };';
  pageScript += '  async function loadComments() {';
  pageScript += '    try {';
  pageScript += '      const res = await fetch("/api/comments/post/" + postId);';
  pageScript += '      const data = await res.json();';
  pageScript += '      if (data.code === 200) renderComments(data.data);';
  pageScript += '    } catch(e) { console.error(e); }';
  pageScript += '  }';
  pageScript += '  window.replyTo = function(username) {';
  pageScript += '    const textarea = document.getElementById("commentContent");';
  pageScript += '    textarea.value = "@" + username + " ";';
  pageScript += '    textarea.focus();';
  pageScript += '    textarea.scrollIntoView({ behavior: "smooth", block: "center" });';
  pageScript += '  };';
  pageScript += '  window.toggleLike = async function() {';
  pageScript += '    const token = localStorage.getItem("token");';
  pageScript += '    if (!token) { openModal("loginModal"); return; }';
  pageScript += '    try {';
  pageScript += '      const res = await authFetch("/api/posts/" + postId + "/like", { method: "POST" });';
  pageScript += '      const data = await res.json();';
  pageScript += '      if (data.code === 200) {';
  pageScript += '        const btn = document.getElementById("likeBtn");';
  pageScript += '        if (data.data.liked) { btn.classList.add("liked"); postData.like_count++; }';
  pageScript += '        else { btn.classList.remove("liked"); postData.like_count--; }';
  pageScript += '        btn.querySelector("span").textContent = postData.like_count;';
  pageScript += '        showToast(data.message, "success");';
  pageScript += '      }';
  pageScript += '    } catch(e) { showToast("操作失败", "error"); }';
  pageScript += '  };';
  pageScript += '  async function loadRelatedPosts(type) {';
  pageScript += '    try {';
  pageScript += '      const res = await fetch("/api/posts?type=" + type + "&limit=8");';
  pageScript += '      const data = await res.json();';
  pageScript += '      if (data.code === 200 && data.data.posts.length > 0) {';
  pageScript += '        const filtered = data.data.posts.filter(p => p.id != postId).slice(0, 6);';
  pageScript += '        document.getElementById("relatedPosts").innerHTML = filtered.map((p, i) =>';
  pageScript += '          \'<div class="hot-list-item"><span class="rank">\' + (i+1) + \'</span><span class="text"><a href="/post/\' + p.id + \'">\' + escapeHtml(p.title) + \'</a></span></div>\'';
  pageScript += '        ).join("");';
  pageScript += '      } else { document.getElementById("relatedPosts").innerHTML = \'<p style="font-size:0.88rem;color:var(--muted);">暂无相关文章</p>\'; }';
  pageScript += '    } catch(e) { console.error(e); }';
  pageScript += '  }';
  pageScript += '  loadPost();';
  pageScript += '})();';
  pageScript += '</script>';
